//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema_Listing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cinema_Listing()
        {
            this.Reserves = new HashSet<Reserve>();
        }
    
        public int Cinema_Listing_ID { get; set; }
        public System.DateTime Day { get; set; }
        public System.TimeSpan Start_Time { get; set; }
        public System.TimeSpan Ending_Time { get; set; }
        public int Cinema_Room_ID { get; set; }
        public int Movie_ID { get; set; }
    
        public virtual Cinema_Room Cinema_Room { get; set; }
        public virtual Movie Movie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserve> Reserves { get; set; }
    }
}
