//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema_Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cinema_Room()
        {
            this.Cinema_Listing = new HashSet<Cinema_Listing>();
        }
    
        public int Cinema_Room_ID { get; set; }
        public byte Room_Rows { get; set; }
        public byte Seating { get; set; }
        public bool Availability_booking { get; set; }
        public int Cinema_Room_Type_ID { get; set; }
        public string Cinema_Name { get; set; }
        public string Province_ID { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cinema_Listing> Cinema_Listing { get; set; }
        public virtual Cinema_Room_Type Cinema_Room_Type { get; set; }
    }
}
