//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int CreditCard_ID { get; set; }
        public System.DateTime Expiry_Date { get; set; }
        public byte[] Number { get; set; }
        public string CVV { get; set; }
        public string Proprietary_Name { get; set; }
        public int User_ID { get; set; }
        public int CreditCard_Type_ID { get; set; }
    
        public virtual CreditCard_Type CreditCard_Type { get; set; }
        public virtual TUser TUser { get; set; }
    }
}
