//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int Phone_ID { get; set; }
        public string Number { get; set; }
        public int Phone_Type_ID { get; set; }
        public int User_ID { get; set; }
    
        public virtual Phone_Type Phone_Type { get; set; }
        public virtual TUser TUser { get; set; }
    }
}
