//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Reserve_ID { get; set; }
        public int User_ID { get; set; }
        public System.DateTime Purchase_Date { get; set; }
    
        public virtual Reserve Reserve { get; set; }
        public virtual TUser TUser { get; set; }
    }
}
